### ISSUE TITLE
Doesn't work with Unicode

### ISSUE THREAD

**Issue by dmaahs2017** [zenoxygen/bayespam#2]
Consider using [Unicode-Segmentation](https://crates.io/crates/unicode-segmentation) crates `split_at_word_bounds` function to break up into unicode words in your `load_word_list` function.

**Comment by thomasdidion** [comment]
Hi @dmaahs2017, thanks for your contribution.
Unicode support was added in the last version (v1.1.0).

**Comment by dmaahs2017** [comment]
Awesome, thanks!
